name: Build

on:
  push:
    branches: [ '*' ]
    tags:
      - v*
  pull_request:
    branches: [ master ]

jobs:
  build-docker:
    runs-on: ${{ matrix.os }}
    container: docker://hhmhh/weylus_build:latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        include:
        - os: ubuntu-latest
          build-cmd: ./docker_build.sh
          package-files: |
            packages/weylus-linux.zip
            packages/Weylus*.deb
            packages/weylus-windows.zip
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: deps/dist
        key: ${{ runner.os }}-deps-${{ hashFiles('deps/*') }}
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
    - name: Build
      run: ${{ matrix.build-cmd }}
      shell: bash
    - name: Package
      run: ${{ matrix.pkg-cmd }}
    - name: Artifacts1
      uses: actions/upload-artifact@v2
      with:
        name: linux
        path: packages/weylus-linux.zip
    - name: Artifacts2
      uses: actions/upload-artifact@v2
      with:
        name: linux-deb
        path: packages/Weylus*.deb
    - name: Artifacts3
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: packages/weylus-windows.zip
    - name: Publish
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: |
            ${{ matrix.package-files }}
          prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest]
        include:
        - os: macOS-latest
          install-deps: |
             npm install -g typescript
             brew install nasm
             cargo install cargo-bundle
          # build-cmd: MACOSX_DEPLOYMENT_TARGET=10.13 cargo bundle --release
          build-cmd: cargo bundle --release
          package-files: target/release/bundle/osx/macOS.zip
          exec-file: target/release/bundle/osx/macOS.zip
          pkg-cmd: cd target/release/bundle/osx/ && zip -r macOS.zip Weylus.app
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: deps/dist
        key: ${{ runner.os }}-deps-${{ hashFiles('deps/*') }}-6
    - uses: actions/cache@v2
      if: ${{ !contains(matrix.os, 'macOS') }}
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}-6
    - name: Download deps
      run: ${{ matrix.install-deps }}
      shell: bash
    - name: Build
      run: ${{ matrix.build-cmd }}
    - name: Package
      run: ${{ matrix.pkg-cmd }}
    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ runner.os }}
        path: |
          ${{ matrix.exec-file }}
    - name: ArtifactsDebug
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: ${{ runner.os }}-ffbuild
        path: |
          deps/ffmpeg/ffbuild
    - name: Debug via SSH
      if: failure()
      uses: luchihoratiu/debug-via-ssh@main
      with:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        SSH_PASS: ${{ secrets.SSH_PASS }}
        NGROK_REGION: eu
    - name: Publish
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: |
            ${{ matrix.package-files }}
          prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
